apiVersion: apps/v1
kind: Deployment
metadata:
  name: farosolutions-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farosolutions-app
  template:
    metadata:
      labels:
        app: farosolutions-app
    spec:
      containers:
      - name: farosolutions-app
        image: farotestregistry.azurecr.io/jebara7/farosolutions-app:latest
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: farosolutions-app-svc
spec:
  selector:
    app: farosolutions-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
